#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2023, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# snap_create host:parent_image snap_id vmid ds_id

SRC=$1
SNAP_ID=$2
VM_ID=$3
DS_ID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON
source ${DRIVER_PATH}/../../datastore/zfs/zfs.conf

#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------

SRC_HOST=`arg_host $SRC`
SRC_PATH=`arg_path $SRC`

SNAPSHOT_NAME="one-snapshot-${SNAP_ID}"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

if [ "$SRC_HOST" != "localhost" ]; then 
    ZVOL=$(ssh ${SRC_HOST} readlink ${SRC_PATH} | awk -F '/' '{ print $NF }' )
    ZPOOL=$(ssh ${SRC_HOST} readlink ${SRC_PATH} | awk -F '/' '{ print $(NF-1) }' )
else
    ZVOL=$(readlink ${SRC_PATH} | awk -F '/' '{ print $NF }' )
    ZPOOL=$(readlink ${SRC_PATH} | awk -F '/' '{ print $(NF-1) }' )
fi

#-------------------------------------------------------------------------------
# Create snapshots
#-------------------------------------------------------------------------------

log "Create snapshot of ${ZVOL}"

DUMP_CMD=$(cat <<EOF
    set -e
    $SUDO $ZFS_CMD snapshot ${ZPOOL}/${ZVOL}@${SNAPSHOT_NAME}
EOF
)

ssh_exec_and_log "${SRC_HOST}" "${DUMP_CMD}" \
                 "Error create snapshot ${SRC_HOST}:${ZPOOL}/${ZVOL}@${SNAPSHOT_NAME}"

exit 0